server:
  port: 9180
spring:
  application:
    name: auth-service
  security:
    oauth2:
      authorizationserver:
        client:
          client-server-oidc:
            registration:
              client-id: client-server
              client-secret: '{noop}secret'
              client-name: client-server
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://127.0.0.1:9999/login/oauth2/code/client-server-oidc
              scopes:
                - openid
                - profile
            require-authorization-consent: true
